[package]
name = "evenio"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["evenio_macros"]

[dependencies]
ahash = "0.8.3"
bumpalo = "3.14.0"
evenio_macros = { path = "evenio_macros" }
rayon = { version = "1.8.0", optional = true }
slab = "0.4.9"

[dev-dependencies]
divan = "0.1.2"
